import {
  Beaker,
  Bell,
  BookOpen,
  Box,
  Boxes,
  Building2,
  ClipboardList,
  Database,
  Droplets,
  Factory,
  FileText,
  FlaskConical,
  Folder,
  Globe,
  Layers,
  Leaf,
  type LucideIcon,
  Package,
  Pill,
  Search,
  Settings,
  ShieldCheck,
  Table2,
  Tag,
  Truck,
  Users,
  Wrench,
} from 'lucide-react'

const registry: Record<string, LucideIcon> = {
  beaker: Beaker,
  bell: Bell,
  book: BookOpen,
  box: Box,
  boxes: Boxes,
  building: Building2,
  clipboard: ClipboardList,
  database: Database,
  droplets: Droplets,
  factory: Factory,
  file: FileText,
  flask: FlaskConical,
  folder: Folder,
  globe: Globe,
  layers: Layers,
  leaf: Leaf,
  package: Package,
  pill: Pill,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  table: Table2,
  tag: Tag,
  truck: Truck,
  users: Users,
  wrench: Wrench,
}

export const iconNames = Object.keys(registry)

export function resolveIcon(name: string | undefined): LucideIcon {
  if (!name) return Box
  return registry[name.toLowerCase()] ?? Box
}
